// Trading service (plan §8, §11.3) — browser sends ONLY asset, quantity and
// an idempotency key. The key MUST be generated by the calling component once
// per order attempt and reused across retries of that same attempt, so a
// double-submit/retry replays instead of duplicating the trade.
// Prices/balances are always server-computed.
import { coins } from '../lib/supabase';
import { mapRpcError } from './errorMapper';
import type { TradeResult, PortfolioRow, TradeRow, WalletRow } from '../types/database';

export async function buyCoin(
  assetId: number, quantity: number, idempotencyKey: string,
): Promise<TradeResult> {
  const { data, error } = await coins().rpc('buy_coin', {
    p_asset_id: assetId,
    p_quantity: quantity,
    p_idempotency_key: idempotencyKey,
  });
  if (error) throw mapRpcError(error);
  return data as TradeResult;
}

export async function sellCoin(
  assetId: number, quantity: number, idempotencyKey: string,
): Promise<TradeResult> {
  const { data, error } = await coins().rpc('sell_coin', {
    p_asset_id: assetId,
    p_quantity: quantity,
    p_idempotency_key: idempotencyKey,
  });
  if (error) throw mapRpcError(error);
  return data as TradeResult;
}

export async function fetchPortfolio(): Promise<PortfolioRow[]> {
  const { data, error } = await coins()
    .from('my_portfolio')
    .select('*')
    .order('current_value', { ascending: false });
  if (error) throw mapRpcError(error);
  return data as PortfolioRow[];
}

export async function fetchWallet(): Promise<WalletRow | null> {
  const { data, error } = await coins()
    .from('wallets')
    .select('user_id, cash_balance, version')
    .maybeSingle();
  if (error) throw mapRpcError(error);
  return data as WalletRow | null;
}

export async function fetchMyTrades(limit = 100): Promise<TradeRow[]> {
  const { data, error } = await coins()
    .from('my_trades')
    .select('*')
    .limit(limit);
  if (error) throw mapRpcError(error);
  return data as TradeRow[];
}
